# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # check swift tests
  mactest:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: xcode-select
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: test
      run: swift test
    - name: release build
      run: swift build --configuration release
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: binaries
        path: |
           .build/x86_64-apple-macosx/release/clisect
           .build/x86_64-apple-macosx/release/clisect.dSYM

  linuxtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: swift test
      run: swift test
    - name: release build
      run: |
        swift build --configuration release
        ldd .build/release/clisect
